import com.android.build.api.dsl.CommonExtension
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import java.io.File

class GradleManagedDevicesPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        target.plugins.withId("com.android.application") {
            target.extensions.configure<com.android.build.api.dsl.ApplicationExtension> {
                configureManagedDevices(this)
            }
        }
        target.plugins.withId("com.android.library") {
            target.extensions.configure<com.android.build.api.dsl.LibraryExtension> {
                configureManagedDevices(this)
            }
        }

        // Register task to fix DNS for GMD emulators on Linux with systemd-resolved.
        // On Arch Linux (and similar), /etc/resolv.conf points to 127.0.0.53 which is
        // unreachable from the emulator's network namespace.
        // This wrapper script intercepts emulator launches and injects -dns-server flag.
        val fixGmdDnsTask = target.tasks.register("fixGmdDns") {
            group = "android"
            description = "Install emulator wrapper to inject -dns-server flag for GMD on Linux"

            // Never consider this task up-to-date (host DNS or emulator state may change)
            outputs.upToDateWhen { false }

            doLast {
                val osName = System.getProperty("os.name", "").lowercase()
                if (!osName.contains("linux")) {
                    println("fixGmdDns: Skipping (not running on Linux)")
                    return@doLast
                }

                val resolvedConf = File("/run/systemd/resolve/resolv.conf")
                if (!resolvedConf.exists()) {
                    println("fixGmdDns: Skipping (systemd-resolved not active)")
                    return@doLast
                }

                // Parse DNS servers from systemd-resolved config
                val dnsServers = resolvedConf.readLines()
                    .filter { it.trim().startsWith("nameserver") }
                    .map { it.substringAfter("nameserver").trim() }
                    .filter { it != "127.0.0.53" } // Exclude stub resolver
                    .distinct()
                    .take(4) // Emulator supports up to 4 DNS servers
                    .takeIf { it.isNotEmpty() }
                    ?: listOf("8.8.8.8", "8.8.4.4") // Fallback to Google DNS

                val dnsServerArg = dnsServers.joinToString(",")

                // Locate Android SDK emulator binary
                val sdkDir = File(System.getenv("ANDROID_HOME") ?: System.getProperty("user.home") + "/Android/Sdk")

                if (!sdkDir.exists()) {
                    println("fixGmdDns: ERROR - Android SDK not found at ${sdkDir.absolutePath}")
                    return@doLast
                }

                val emulatorDir = File(sdkDir, "emulator")
                val emulatorBin = File(emulatorDir, "emulator")
                val emulatorReal = File(emulatorDir, "emulator.real")

                if (!emulatorBin.exists()) {
                    println("fixGmdDns: ERROR - Emulator binary not found at ${emulatorBin.absolutePath}")
                    return@doLast
                }

                // Rename original binary if not already done
                if (!emulatorReal.exists()) {
                    if (!emulatorBin.renameTo(emulatorReal)) {
                        println("fixGmdDns: ERROR - Failed to rename emulator to emulator.real")
                        return@doLast
                    }
                    println("fixGmdDns: Renamed emulator binary to emulator.real")
                }

                // Write wrapper script
                val wrapperContent = """#!/bin/bash
# Emulator DNS wrapper (generated by fixGmdDns task)
# Injects -dns-server flag to fix DNS resolution on systemd-resolved systems
SCRIPT_DIR="${'$'}(cd "${'$'}(dirname "${'$'}0")" && pwd)"
exec "${'$'}SCRIPT_DIR/emulator.real" -dns-server $dnsServerArg "${'$'}@"
"""
                emulatorBin.writeText(wrapperContent)
                emulatorBin.setExecutable(true)

                println("fixGmdDns: Installed emulator wrapper with DNS servers: $dnsServerArg")
                if (emulatorReal.exists()) {
                    println("fixGmdDns: To restore original emulator, run: ./gradlew :mobile:app:restoreEmulator")
                }
            }
        }

        // Register task to restore original emulator binary
        target.tasks.register("restoreEmulator") {
            group = "android"
            description = "Remove emulator DNS wrapper and restore original binary"

            doLast {
                val sdkDir = File(System.getenv("ANDROID_HOME") ?: System.getProperty("user.home") + "/Android/Sdk")

                val emulatorDir = File(sdkDir, "emulator")
                val emulatorBin = File(emulatorDir, "emulator")
                val emulatorReal = File(emulatorDir, "emulator.real")

                if (!emulatorReal.exists()) {
                    println("restoreEmulator: Nothing to restore (emulator.real not found)")
                    return@doLast
                }

                // Delete wrapper and restore original
                if (!emulatorBin.delete() && emulatorBin.exists()) {
                    println("restoreEmulator: ERROR - Failed to delete wrapper (file may be in use)")
                    return@doLast
                }
                if (emulatorReal.renameTo(emulatorBin)) {
                    println("restoreEmulator: Restored original emulator binary")
                } else {
                    println("restoreEmulator: ERROR - Failed to rename emulator.real back to emulator")
                }
            }
        }

        // Wire DNS fix to run before pixel6Api36Setup
        target.tasks.configureEach {
            if (name == "pixel6Api36Setup") {
                dependsOn(fixGmdDnsTask)
            }
        }
    }

    private fun configureManagedDevices(android: CommonExtension<*, *, *, *, *, *>) {
        android.testOptions {
            animationsDisabled = true

            managedDevices {
                localDevices.maybeCreate("pixel6Api36").apply {
                    device = "Pixel 6"
                    apiLevel = 36
                    systemImageSource = "google_apis_playstore"
                    testedAbi = "x86_64"
                }

                groups.maybeCreate("phone").apply {
                    targetDevices.addAll(localDevices.matching { it.name == "pixel6Api36" })
                }
            }
        }
    }
}
